# Site settings
title: Thaiane Braga
description: Um site sobre estudos, projetos, programação, engenharia de software, feminismo, bipolaridade, vida, universo e tudo mais. 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Thai Braga
user_description: Sou apaixonada por programação, seja a criação desafiadora de um novo framework ou um aplicativo para uma tia. 

Também já atuei na área de gestão de projetos sendo uma ótima oportunidade de intensificar e práticar os meus conhecimentos em desenvolver pessoas, analisar requisitos, contato com clientes, modelagem e melhoria de processos e auxiliar na melhoria contínua do trabalho da equipe baseando-se nos valores ágeis. 

Atualmente, além de contribuir no desenvolvimento de microserviços, busco aprender e aplicar temas relacionados à segurança da informação.
user_title: Engenheira de Software
email: thaianefbraga@gmail.com
github_username:  Thaiane

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
